name: flutter_state_value_example
description: A sample with a basic example

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.0.1

  value_state: 1.5.1
  flutter_value_state: 1.3.5
  value_cubit: 1.3.2
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
