name: value_state
description: Dart package for handling loading, error, and data states.
version: 2.0.0
repository: https://github.com/devobs/value_state
homepage: https://github.com/devobs
topics: [error, fetch, init, state, success]

environment:
  sdk: ^3.4.0

dependencies:
  meta: ^1.7.0
  stream_transform: ^2.0.0
  
dev_dependencies:
  lints: ^5.0.0
  test: ^1.20.1
