name: value_state_example
description: A sample with a basic example

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.6
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  value_state: ^2.0.0-beta.1
    
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  riverpod_generator: ^2.6.3
  build_runner: ^2.4.13
  custom_lint: ^0.7.0
  riverpod_lint: ^2.6.3

  meta: ^1.7.0

flutter:
  uses-material-design: true
