name: flutter_value_state
description: A dart package that helps implements basic states for BLoC library
repository: https://github.com/devobs/value_state
homepage: https://github.com/devobs
version: 1.2.0

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  value_state: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  test: ^1.20.1
  stream_transform: ^2.0.0
